language: c
sudo: required
dist: zesty

env:
  matrix:
    - EMACS=emacs
    - EMACS=emacs25

# branches:
#   only:
#     - master

install:
  - if [ "$EMACS" = 'emacs24' ]; then
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs;
    fi
  - if [ "$EMACS" = 'emacs25' ]; then
        sudo add-apt-repository -y ppa:kelleyk/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs25;
    fi

script:
  - $EMACS --version
  - $EMACS --batch --eval '(progn (push "." load-path) (byte-compile-file "tickscript-mode.el"))'
  - $EMACS -batch -L . -l ert -l tickscript-mode-tests.el -f  ert-run-tests-batch-and-exit;

notifications:
  email: true
